version: '3'

services:
  app:
    build: .
    container_name: app
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn The6ix.wsgi -b 0.0.0.0:8000"
    networks:
      - dbnet
    ports:
      - 8000:8000
    environment:
      aws_access_key_id: ${aws_access_key_id}
      aws_secret_access_key: ${aws_secret_access_key}

networks:
  dbnet:
    external: true