version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    command: gunicorn The6ix.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    networks:
      - dbnet
    expose:
      - 8000
    environment:
      aws_access_key_id: ${aws_access_key_id}
      aws_secret_access_key: ${aws_secret_access_key}

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:


networks:
  dbnet:
    external: true