version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn The6ix.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    networks:
      - dbnet
      - nginx_network
    ports:
      - "8000:8000"
    environment:
      aws_access_key_id: ${aws_access_key_id}
      aws_secret_access_key: ${aws_secret_access_key}

  redis:
    image: redis:latest
    networks:
      - dbnet
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web
    networks:
      - nginx_network

  database:
    image: "postgres" # use latest official postgres version
    restart: unless-stopped
    env_file:
      - ./database.env # configure postgres
    networks:
      - dbnet
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data:
  static_volume:
  media_volume:


networks:
  dbnet:
    external: true
  nginx_network:
    external: true