version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    command: gunicorn The6ix.wsgi --bind 0.0.0.0:8000
    networks:
      - dbnet
    ports:
      - 8000:8000
    environment:
      aws_access_key_id: ${aws_access_key_id}
      aws_secret_access_key: ${aws_secret_access_key}

networks:
  dbnet:
    external: true