FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/mediafiles
WORKDIR $APP_HOME

COPY requirements.txt $APP_HOME

RUN pip install -r $APP_HOME/requirements.txt

RUN pip install --upgrade boto3
RUN pip install --upgrade psycopg2
RUN pip install --upgrade gunicorn

COPY . $APP_HOME




