# Generated by Django 4.0 on 2022-06-10 18:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('task_id', models.CharField(max_length=36)),
                ('rept_name', models.CharField(max_length=255)),
                ('rept_type', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=12)),
                ('created', models.DateTimeField()),
                ('completed', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
