# Generated by Django 4.0 on 2022-06-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashstats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='perc_complete',
            field=models.IntegerField(default=0),
        ),
    ]
